import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { _resetDbForTests, getDb } from "../db/index";
import {
  createBacklogItem,
  listBacklog,
  triageBacklogItem,
} from "../db/backlog";
import {
  archiveStaleProposals,
  importIdeas,
  parseIdeaSpec,
  scanIdeasFolder,
} from "./ideas-folder";

let root: string;
let ideas: string;

beforeEach(() => {
  _resetDbForTests();
  root = mkdtempSync(join(tmpdir(), "drydock-ideas-"));
  process.env.DRYDOCK_DB_PATH = join(root, "test.db");
  ideas = join(root, "autogenerated-ideas");
  mkdirSync(ideas, { recursive: true });
  getDb();
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

function spec(file: string, body: string): void {
  writeFileSync(join(ideas, file), body);
}

/** The real shape, taken from `~/Projects/autogenerated-ideas`. */
const LIVE = `# PermitFlow — Federal-State Infrastructure Permit Tracker

> **Generated:** 2026-03-09 | **Sector:** Infrastructure Permitting

---

## Problem Statement

Infrastructure permitting in the U.S. is undergoing its most dramatic overhaul in decades. Another sentence follows.
`;

/** A spec that was later merged into another — same file, restyled heading. */
const MERGED = `# ~~PermitClock~~ — MERGED into #67 NWPNavigator (2026-05-31)

> **Status: MERGED** — PermitClock's features were absorbed into #67.

> **Generated:** 2026-03-15 | **Sector:** Infrastructure Permitting

## Problem Statement

On March 15, 2026, the Corps' 2021 Nationwide Permits expired.
`;

describe("parseIdeaSpec", () => {
  it("reads title, sector, generated date, and a one-line pitch", () => {
    const parsed = parseIdeaSpec("12-permitflow-spec.md", LIVE)!;
    expect(parsed.title).toBe(
      "PermitFlow — Federal-State Infrastructure Permit Tracker",
    );
    expect(parsed.sector).toBe("Infrastructure Permitting");
    expect(parsed.generated).toBe("2026-03-09");
    expect(parsed.superseded).toBe(false);
  });

  it("does NOT truncate a pitch at an abbreviation", () => {
    // A naive split on ". " cuts this to "Infrastructure permitting in
    // the U.S." — grammatical, meaningless, and useless for triage.
    const parsed = parseIdeaSpec("12-permitflow-spec.md", LIVE)!;
    expect(parsed.pitch).toBe(
      "Infrastructure permitting in the U.S. is undergoing its most dramatic overhaul in decades.",
    );
  });

  it("flags a merged spec and cleans its title", () => {
    // These files keep their name and restyle the heading. Proposing one
    // would resurrect a dead idea — every single night.
    const parsed = parseIdeaSpec("28-permitclock-spec.md", MERGED)!;
    expect(parsed.superseded).toBe(true);
    expect(parsed.title).toBe("PermitClock");
    expect(parsed.supersededNote).toContain("MERGED");
  });

  it("does not treat a plain strikethrough as merged", () => {
    // `~~` is also used for emphasis; the explicit word is required.
    const parsed = parseIdeaSpec("x.md", "# ~~Old Name~~ NewName\n")!;
    expect(parsed.superseded).toBe(false);
  });

  it("returns null for a file with no heading", () => {
    expect(parseIdeaSpec("x.md", "just prose\n")).toBeNull();
    expect(parseIdeaSpec("x.md", "")).toBeNull();
  });

  it("tolerates a spec with no metadata line or problem statement", () => {
    const parsed = parseIdeaSpec("x.md", "# Bare Idea\n\nSome text.\n")!;
    expect(parsed.title).toBe("Bare Idea");
    expect(parsed.generated).toBeNull();
    expect(parsed.pitch).toBeNull();
  });
});

describe("scanIdeasFolder", () => {
  it("separates live specs from superseded ones", () => {
    spec("12-permitflow-spec.md", LIVE);
    spec("28-permitclock-spec.md", MERGED);
    return scanIdeasFolder(ideas).then((scan) => {
      expect(scan.specs.map((s) => s.title)).toEqual([
        "PermitFlow — Federal-State Infrastructure Permit Tracker",
      ]);
      expect(scan.supersededCount).toBe(1);
    });
  });

  it("says why rather than silently returning nothing", async () => {
    const scan = await scanIdeasFolder(join(root, "nope"));
    expect(scan.specs).toEqual([]);
    expect(scan.reason).toContain("no ideas folder");
  });

  it("ignores non-markdown files", async () => {
    spec("notes.txt", "# Not a spec");
    spec("12-permitflow-spec.md", LIVE);
    const scan = await scanIdeasFolder(ideas);
    expect(scan.specs).toHaveLength(1);
  });
});

describe("importIdeas", () => {
  it("lands specs as PROPOSED inbox rows, never in the backlog", () => {
    spec("12-permitflow-spec.md", LIVE);
    return importIdeas(ideas).then((result) => {
      expect(result.proposed).toBe(1);
      expect(listBacklog({ stage: "triaged" })).toHaveLength(0);
      const [item] = listBacklog({ stage: "inbox" });
      expect(item.status).toBe("proposed");
      expect(item.source).toBe("ai-generated");
      expect(item.description).toContain("Sector: Infrastructure Permitting");
      expect(item.description).toContain("file://");
    });
  });

  it("never proposes a superseded spec", async () => {
    spec("28-permitclock-spec.md", MERGED);
    const result = await importIdeas(ideas);
    expect(result.proposed).toBe(0);
    expect(result.supersededSkipped).toBe(1);
    expect(listBacklog()).toHaveLength(0);
  });

  it("is idempotent by filename", async () => {
    spec("12-permitflow-spec.md", LIVE);
    await importIdeas(ideas);
    const second = await importIdeas(ideas);
    expect(second.proposed).toBe(0);
    expect(listBacklog()).toHaveLength(1);
  });

  it("refreshes a rewritten spec in place", async () => {
    spec("12-permitflow-spec.md", LIVE);
    await importIdeas(ideas);
    spec("12-permitflow-spec.md", LIVE.replace("PermitFlow", "PermitFlow v2"));
    const second = await importIdeas(ideas);

    expect(second.refreshed).toBe(1);
    const rows = listBacklog();
    expect(rows).toHaveLength(1);
    expect(rows[0].title).toContain("PermitFlow v2");
  });
});

describe("archiveStaleProposals", () => {
  it("drops proposals nobody accepted within the window", () => {
    // They accumulate until the inbox is unopenable. The spec files stay
    // on disk, so a re-import brings anything back.
    const now = 2_000_000;
    const old = createProposal("stale idea", now - 40 * 86_400);
    const fresh = createProposal("fresh idea", now - 2 * 86_400);

    expect(archiveStaleProposals(now)).toBe(1);
    const rows = listBacklog();
    expect(rows.find((r) => r.id === old.id)!.status).toBe("dropped");
    expect(rows.find((r) => r.id === fresh.id)!.status).toBe("proposed");
  });

  it("leaves accepted items alone regardless of age", async () => {
    spec("12-permitflow-spec.md", LIVE);
    await importIdeas(ideas);
    const [item] = listBacklog({ stage: "inbox" });
    triageBacklogItem(item.id);

    expect(archiveStaleProposals(2_000_000)).toBe(0);
    expect(listBacklog()[0].status).toBe("idea");
  });
});

function createProposal(title: string, createdAt: number) {
  return createBacklogItem({
    title,
    source: "ai-generated",
    status: "proposed",
    created_at: createdAt,
  });
}
