import { promises as fs } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { intakeCapture } from "../orchestrator/intake";
import { listBacklog, updateBacklogItem } from "../db/backlog";

/**
 * The nightly idea generator → DryDock's inbox (EP-14 Spec B).
 *
 * `autogenerated-ideas` has been running at 03:33 for 113+ nights and
 * writes spec files that **nothing reads**. This connector closes that
 * loop: each spec becomes a `proposed` inbox row, so the ideas show up
 * where the user already triages instead of accumulating in a folder.
 *
 * ── The fallback path, not the primary one ──────────────────────────────
 * The plan's primary route is the skill calling `add_backlog_item` over
 * MCP as it writes each spec. This folder scan is the fallback for when
 * that call fails or the skill hasn't been updated — and both land
 * identically (`source='ai-generated'`, `status='proposed'`,
 * `external_id='idea:<filename>'`), so running both is harmless.
 *
 * ── Superseded specs must not be re-proposed ────────────────────────────
 * These files get merged into one another over time and the merged one
 * keeps its file, restyled: `# ~~PermitClock~~ — MERGED into #67`. A
 * naive title read would propose a dead idea, and re-propose it every
 * night. Detecting that state is most of the parsing work here.
 */

export const DEFAULT_IDEAS_DIR = join(
  homedir(),
  "Projects",
  "autogenerated-ideas",
);

export interface IdeaSpec {
  /** Filename, e.g. `28-permitclock-spec.md`. The stable identity. */
  file: string;
  title: string;
  /** First substantive line of the problem statement, trimmed. */
  pitch: string | null;
  /** `2026-03-15` from the `**Generated:**` line, when present. */
  generated: string | null;
  sector: string | null;
  /**
   * True when the spec says it was merged, superseded, or dropped. These
   * are read but never proposed — re-proposing a dead idea every night
   * is how a triage queue becomes noise the user stops opening.
   */
  superseded: boolean;
  supersededNote: string | null;
}

/** Ways these files mark a spec as no longer live. */
const SUPERSEDED = /\b(MERGED|SUPERSEDED|ABSORBED|DEPRECATED|DROPPED)\b/;

export function parseIdeaSpec(file: string, content: string): IdeaSpec | null {
  const lines = content.split(/\r?\n/);
  const headingIndex = lines.findIndex((l) => l.trimStart().startsWith("# "));
  if (headingIndex === -1) return null;

  const heading = lines[headingIndex].replace(/^\s*#\s*/, "").trim();
  if (heading.length === 0) return null;

  // A merged spec keeps its file and restyles the heading:
  //   `# ~~PermitClock~~ — MERGED into #67 NWPNavigator (2026-05-31)`
  // The strikethrough alone isn't proof (it's also used for emphasis),
  // so require the explicit word too — and check the status blockquote
  // that follows, which is where a later-added note lands.
  const blockquote = lines
    .slice(headingIndex + 1, headingIndex + 8)
    .filter((l) => l.trimStart().startsWith(">"))
    .join(" ");
  const superseded =
    SUPERSEDED.test(heading) || /Status:\s*\**\s*(MERGED|SUPERSEDED)/i.test(blockquote);

  // Strip the strikethrough and any trailing "— MERGED into …" clause so
  // the title reads as the idea's actual name.
  const title = heading
    .replace(/~~/g, "")
    .replace(/\s*[—-]\s*(MERGED|SUPERSEDED|ABSORBED|DEPRECATED|DROPPED)\b.*$/i, "")
    .trim();
  if (title.length === 0) return null;

  const meta = lines.slice(0, headingIndex + 12).join("\n");
  const generated = meta.match(/\*\*Generated:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})/);
  const sector = meta.match(/\*\*Sector:\*\*\s*([^|\n]+)/);

  return {
    file,
    title,
    pitch: firstProblemSentence(lines),
    generated: generated ? generated[1] : null,
    sector: sector ? sector[1].trim() : null,
    superseded,
    supersededNote: superseded ? summarize(heading) : null,
  };
}

/**
 * One sentence from the Problem Statement — enough to decide whether to
 * accept without opening the file, which is the whole point of a triage
 * queue. Bounded so a run-on paragraph can't fill the inbox card.
 */
function firstProblemSentence(lines: string[]): string | null {
  const start = lines.findIndex((l) => /^##\s+Problem Statement/i.test(l.trim()));
  if (start === -1) return null;
  for (let i = start + 1; i < Math.min(lines.length, start + 20); i += 1) {
    const line = lines[i].trim();
    if (line.length === 0 || line.startsWith(">") || line.startsWith("#")) {
      continue;
    }
    const sentence = firstSentence(line);
    if (sentence.length < 20) continue;
    return sentence.length > 280 ? `${sentence.slice(0, 277)}…` : sentence;
  }
  return null;
}

/**
 * Split off the first sentence without being fooled by abbreviations.
 *
 * A naive split on `". "` truncates "Infrastructure permitting in the
 * U.S. is slow" to "Infrastructure permitting in the U.S." — which is
 * grammatical, meaningless, and exactly the kind of half-thought that
 * makes a triage queue useless. Requiring the character before the
 * period to be lowercase or a digit skips `U.S.`, `Inc.`, and initials,
 * because a real sentence essentially never ends on a capital letter.
 */
function firstSentence(line: string): string {
  const match = line.match(/^(.*?[a-z0-9]\.)\s+[A-Z"“(]/);
  return (match ? match[1] : line).trim();
}

function summarize(heading: string): string {
  const cleaned = heading.replace(/~~/g, "").trim();
  return cleaned.length > 160 ? `${cleaned.slice(0, 157)}…` : cleaned;
}

export interface IdeasScan {
  specs: IdeaSpec[];
  /** Files that parsed but are merged/superseded — read, never proposed. */
  supersededCount: number;
  dir: string;
  reason: string | null;
}

export async function scanIdeasFolder(
  dir: string = DEFAULT_IDEAS_DIR,
): Promise<IdeasScan> {
  let files: string[];
  try {
    files = await fs.readdir(dir);
  } catch {
    return {
      specs: [],
      supersededCount: 0,
      dir,
      reason: `no ideas folder at ${dir}`,
    };
  }

  const specs: IdeaSpec[] = [];
  let supersededCount = 0;
  for (const file of files.sort()) {
    if (!file.endsWith(".md")) continue;
    let content: string;
    try {
      content = await fs.readFile(join(dir, file), "utf8");
    } catch {
      continue;
    }
    const spec = parseIdeaSpec(file, content);
    if (!spec) continue;
    if (spec.superseded) {
      supersededCount += 1;
      continue;
    }
    specs.push(spec);
  }

  return { specs, supersededCount, dir, reason: null };
}

export interface IdeasImport {
  proposed: number;
  refreshed: number;
  duplicates: number;
  supersededSkipped: number;
  dir: string;
  reason: string | null;
}

/**
 * Propose every live spec into the inbox.
 *
 * Idempotent by filename: a spec that gets rewritten updates its existing
 * row rather than adding a second, which matters when the generator
 * refreshes a spec it wrote weeks ago.
 */
export async function importIdeas(
  dir: string = DEFAULT_IDEAS_DIR,
): Promise<IdeasImport> {
  const scan = await scanIdeasFolder(dir);
  const result: IdeasImport = {
    proposed: 0,
    refreshed: 0,
    duplicates: 0,
    supersededSkipped: scan.supersededCount,
    dir: scan.dir,
    reason: scan.reason,
  };

  for (const spec of scan.specs) {
    const description = [
      spec.pitch,
      spec.sector ? `Sector: ${spec.sector}` : null,
      spec.generated ? `Generated ${spec.generated}` : null,
      `file://${join(scan.dir, spec.file)}`,
    ]
      .filter(Boolean)
      .join("\n");

    const outcome = intakeCapture({
      text: spec.title,
      source: "ai-generated",
      externalId: `idea:${spec.file}`,
      description,
      // Machine-generated: `proposed`, never `idea`. Accepting is the
      // human gate, and it's the only thing that moves one of these into
      // the list the user actually trusts.
      status: "proposed",
    });

    if (outcome.outcome === "created") result.proposed += 1;
    else if (outcome.outcome === "updated") result.refreshed += 1;
    else result.duplicates += 1;
  }

  return result;
}

/**
 * Auto-archive stale proposals.
 *
 * A proposal nobody accepted in 30 days is one the user has now declined
 * several times by scrolling past it. Left alone they accumulate until
 * the inbox is unopenable, which costs far more than losing an idea that
 * is still sitting in a spec file on disk — re-running the import
 * re-proposes it, so nothing is actually destroyed.
 */
export const IDEA_ARCHIVE_DAYS = 30;

export function archiveStaleProposals(
  now: number = Math.floor(Date.now() / 1000),
  days: number = IDEA_ARCHIVE_DAYS,
): number {
  const cutoff = now - days * 86_400;
  let archived = 0;
  for (const item of listBacklog({ status: "proposed", stage: "inbox" })) {
    if (item.created_at > cutoff) continue;
    updateBacklogItem(item.id, { status: "dropped" });
    archived += 1;
  }
  return archived;
}
